In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
rainfall = pd.read_csv('./train.csv')
rainfall

,MONTH,YEAR,ANDAMAN & NICOBAR ISLANDS,ARUNACHAL PRADESH,ASSAM & MEGHALAYA,BIHAR,CHHATTISGARH,COASTAL ANDHRA PRADESH,COASTAL KARNATAKA,EAST MADHYA PRADESH,...,SAURASHTRA & KUTCH,SOUTH INTERIOR KARNATAKA,SUB HIMALAYAN WEST BENGAL & SIKKIM,TAMIL NADU,TELANGANA,UTTARAKHAND,VIDARBHA,WEST MADHYA PRADESH,WEST RAJASTHAN,WEST UTTAR PRADESH
0,JAN,1901,49.2,NaN,27.1,51.8,48.9,18.8,1.8,48.5,...,1.9,4.9,26.5,24.5,6.9,134.5,36.8,25.8,6.7,51.4
1,FEB,1901,87.1,NaN,19.5,19.6,116.5,80.9,0.6,38.1,...,0.0,31.8,14.8,39.1,41.8,81.4,39.9,5.8,0.0,25.6
2,MAR,1901,29.2,NaN,30.6,11.9,27.8,7.2,10.7,15.7,...,0.1,3.0,14.1,21.7,7.8,44.5,30.9,5.8,1.1,9.5
3,APR,1901,2.3,NaN,223.0,1.1,5.5,28.7,52.4,10.7,...,0.2,32.7,29.2,36.0,45.2,5.9,26.1,2.8,0.0,0.7
4,MAY,1901,528.8,NaN,207.0,65.6,18.4,68.7,81.6,6.2,...,3.2,109.6,195.5,74.0,22.0,60.8,7.3,2.1,6.1,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1363,AUG,2014,321.6,599.6,484.6,307.6,327.7,177.8,1121.0,231.8,...,118.8,254.6,563.3,117.7,205.2,264.2,191.7,211.0,69.6,81.0
1364,SEP,2014,412.9,343.0,420.2,160.3,252.7,144.5,379.3,139.6,...,99.2,161.6,371.5,98.9,146.8,107.9,224.9,192.6,84.9,84.7
1365,OCT,2014,402.6,35.1,35.0,47.8,77.9,195.6,226.4,56.4,...,5.2,152.9,31.2,252.2,29.6,40.8,17.3,7.0,0.5,14.6
1366,NOV,2014,201.2,20.1,3.0,0.0,2.6,23.7,40.0,1.9,...,2.7,20.2,5.3,110.8,10.8,0.0,6.2,3.0,0.2,0.0
1367,DEC,2014,100.4,10.2,0.4,1.2,1.1,6.4,30.8,12.9,...,0.0,18.7,2.4,66.0,0.7,44.3,2.3,15.8,0.0,16.3